version: "3.3"

services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOTPW} #SQL root Passwort eingeben
      - MYSQL_PASSWORD=${DBPW} #SQL Benutzer Passwort eingeben
      - MYSQL_DATABASE=${DBNAME} #Datenbank Name
      - MYSQL_USER=${DBUSER} #SQL Nutzername
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /media/hdd/nextcloud_data/database:/var/lib/mysql

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - 8008:80
    depends_on:
      - nextcloud-db
    environment:
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: "${URL}"
      OVERWRITEHOST: "${DOMAIN}"
    volumes:
      - /media/hdd/nextcloud_data/app/web:/var/www/html
      - /media/hdd/nextcloud_data/app/data:/var/www/html/data 


